import { defineConfig } from 'tinacms';

export default defineConfig({
  branch: process.env.TINA_BRANCH || process.env.HEAD || 'main',
  clientId: process.env.TINA_CLIENT_ID || '',
  token: process.env.TINA_TOKEN || '',
  build: {
    outputFolder: 'admin',
    publicFolder: 'public',
  },
  media: {
    tina: {
      mediaRoot: 'images',
      publicFolder: 'public',
    },
  },
  schema: {
    collections: [
      {
        name: 'site',
        label: 'Seitenweite Daten',
        path: 'src/content',
        format: 'md',
        match: { include: 'site' },
        ui: { allowedActions: { create: false, delete: false } },
        fields: [
          { type: 'string', name: 'name', label: 'Studio-Name', required: true },
          { type: 'string', name: 'email', label: 'E-Mail', required: true },
          { type: 'string', name: 'phone', label: 'Telefon' },
          { type: 'string', name: 'address', label: 'Adresse' },
          { type: 'string', name: 'instagram', label: 'Instagram URL' },
          { type: 'string', name: 'whatsapp', label: 'WhatsApp Nummer' },
          {
            type: 'object',
            name: 'opening_hours',
            label: 'Öffnungszeiten',
            list: true,
            fields: [
              { type: 'string', name: 'day', label: 'Tag' },
              { type: 'string', name: 'hours', label: 'Zeiten' },
            ],
          },
        ],
      },
      {
        name: 'home',
        label: 'Startseite',
        path: 'src/content',
        format: 'md',
        match: { include: 'home' },
        ui: { allowedActions: { create: false, delete: false } },
        fields: [
          { type: 'string', name: 'hero_title', label: 'Hero Titel', required: true },
          { type: 'string', name: 'hero_subtitle', label: 'Hero Untertitel' },
          { type: 'string', name: 'hero_cta_text', label: 'Hero Button Text' },
          { type: 'string', name: 'hero_cta_link', label: 'Hero Button Link' },
          { type: 'image', name: 'hero_image', label: 'Hero Bild' },
          { type: 'string', name: 'philosophy_quote', label: 'Philosophie Zitat' },
          { type: 'string', name: 'philosophy_cite', label: 'Zitat Quelle' },
          { type: 'string', name: 'about_label', label: 'Über mich Label' },
          { type: 'string', name: 'about_title', label: 'Über mich Titel' },
          { type: 'rich-text', name: 'about_text', label: 'Über mich Text' },
          { type: 'string', name: 'retreat_label', label: 'Retreat Label' },
          { type: 'string', name: 'retreat_title', label: 'Retreat Titel' },
          { type: 'rich-text', name: 'retreat_text', label: 'Retreat Text' },
          {
            type: 'object',
            name: 'testimonials',
            label: 'Testimonials',
            list: true,
            fields: [
              { type: 'string', name: 'quote', label: 'Zitat', required: true },
              { type: 'string', name: 'author', label: 'Autor', required: true },
              { type: 'number', name: 'stars', label: 'Sterne (1-5)' },
            ],
          },
        ],
      },
      {
        name: 'page',
        label: 'Seiten',
        path: 'src/content/pages',
        format: 'md',
        fields: [
          { type: 'string', name: 'title', label: 'Titel', required: true, isTitle: true },
          { type: 'string', name: 'subtitle', label: 'Untertitel' },
          { type: 'string', name: 'seo_description', label: 'SEO Beschreibung' },
          { type: 'rich-text', name: 'body', label: 'Inhalt', isBody: true },
        ],
      },
      {
        name: 'angebot',
        label: 'Angebote',
        path: 'src/content/angebote',
        format: 'md',
        fields: [
          { type: 'string', name: 'title', label: 'Titel', required: true, isTitle: true },
          { type: 'string', name: 'subtitle', label: 'Untertitel' },
          { type: 'string', name: 'seo_description', label: 'SEO Beschreibung' },
          { type: 'rich-text', name: 'body', label: 'Beschreibung', isBody: true },
          { type: 'string', name: 'highlights', label: 'Was dich erwartet', list: true },
          { type: 'string', name: 'target_audience', label: 'Für wen geeignet' },
          { type: 'number', name: 'sort_order', label: 'Reihenfolge (1-6)' },
        ],
      },
      {
        name: 'blog',
        label: 'Blog',
        path: 'src/content/blog',
        format: 'md',
        fields: [
          { type: 'string', name: 'title', label: 'Titel', required: true, isTitle: true },
          { type: 'datetime', name: 'date', label: 'Datum', required: true },
          { type: 'string', name: 'author', label: 'Autor' },
          { type: 'string', name: 'excerpt', label: 'Kurzbeschreibung' },
          { type: 'string', name: 'seo_description', label: 'SEO Beschreibung' },
          { type: 'image', name: 'image', label: 'Beitragsbild' },
          { type: 'rich-text', name: 'body', label: 'Inhalt', isBody: true },
        ],
      },
      {
        name: 'preise',
        label: 'Preise',
        path: 'src/content',
        format: 'md',
        match: { include: 'preise' },
        ui: { allowedActions: { create: false, delete: false } },
        fields: [
          { type: 'string', name: 'title', label: 'Seitentitel', required: true },
          { type: 'string', name: 'subtitle', label: 'Untertitel' },
          { type: 'string', name: 'seo_description', label: 'SEO Beschreibung' },
          {
            type: 'object',
            name: 'sections',
            label: 'Preisgruppen',
            list: true,
            fields: [
              { type: 'string', name: 'label', label: 'Label (klein)' },
              { type: 'string', name: 'title', label: 'Gruppenname' },
              { type: 'string', name: 'description', label: 'Beschreibung' },
              {
                type: 'object',
                name: 'cards',
                label: 'Preiskarten',
                list: true,
                fields: [
                  { type: 'string', name: 'name', label: 'Name' },
                  { type: 'string', name: 'price', label: 'Preis' },
                  { type: 'string', name: 'period', label: 'Zeitraum' },
                  { type: 'string', name: 'features', label: 'Features', list: true },
                  { type: 'boolean', name: 'featured', label: 'Hervorgehoben' },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
});
